UPDATE worf_billing_version SET version = 4;

ALTER TABLE invoice ALTER COLUMN tax DROP DEFAULT;
ALTER TABLE invoice ALTER COLUMN tax DROP NOT NULL;
ALTER TABLE invoice ALTER COLUMN amount DROP DEFAULT;
ALTER TABLE invoice ALTER COLUMN amount DROP NOT NULL;
ALTER TABLE invoice ALTER COLUMN discount DROP DEFAULT;
ALTER TABLE invoice ALTER COLUMN discount DROP NOT NULL;

ALTER TABLE subscription_item DROP COLUMN active;